# string advance methods
print("hello world ".capitalize())
print("hello World ".casefold())
print("hello world".lower())
print("hello world ".upper())
print("hello world".swapcase())
print("hello world ".title())
print("hello world ".find("l"))
print("hello".rfind("o"))
print("hello world ".index("l"))
print("hello".count("l"))
print("hello world ".replace("l","e"))
print("hello,world,test ".split(","))
print("hello world how are you i am fine thank you".rsplit("thank you"))
print("hello\nworld".splitlines())
print("    hello".strip())
print("   hello   ".rstrip())
print("hello world".rsplit("e",1))
print("Hello world".startswith("e"))
print("Hello world".startswith("He"))
print("hello world".endswith("e"))
print("Hello world".endswith("ld"))