# string advance methods
print(",".join(["a","b","c"]))
print("abc".isalpha())
print("abc".isnumeric())
print("abc1232".isalpha())
print("123".isdigit())
print("abc123".isalnum())
print(" ".isspace())
print(" a".isspace())
print("a".isspace())
print(" a ".isspace())
print(len("Hello world"))
print("Hello,{}".format("world"))
print("142".zfill(5))
print("4".zfill(333))
print("Hello".center(10))
print("Hello".ljust(10))
print("hello".rjust(10))